<?php

?>
<?php if ($_entity = $this->getEntity()): ?>
<div id="comments_block">
    <span class="field-row">
        <label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Comment Text') ?></label>
        <textarea name="comment[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
    </span>
    <div class="f-left">
        <?php if ($this->canSendCommentEmail()): ?>
            <input name="comment[is_customer_notified]" type="checkbox" id="history_notify" value="1" />
            <label class="normal" for="history_notify"><?php echo Mage::helper('sales')->__('Notify Customer by Email') ?></label><br />
        <?php endif; ?>
        <input name="comment[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?php echo Mage::helper('sales')->__('Visible on Frontend') ?></label>
    </div>
    <div class="f-right">
        <?php echo $this->getChildHtml('submit_button') ?>
    </div>
    <div class="clear"></div>
    <ul class="note-list">
    <?php foreach ($_entity->getCommentsCollection(true) as $_comment): ?>
    	<?php
			$text = $_comment->getComment();

			if ($text && strpos($text, Telecom_SMSNotifier_Helper_Data::SMS_MARK) === 0)
			{
				$sms	 = true;
				$parts   = explode(';', $text);
				$role    = $parts[1];
				$send    = $parts[2];
				$text = implode(';', array_slice($parts, 3));
			}
		?>
        <li <?php if (isset($sms)) echo 'class="mobil"' ?> >
            <strong><?php echo $this->helper('core')->formatDate($_comment->getCreatedAtDate(), 'medium') ?></strong>
            <?php echo $this->helper('core')->formatTime($_comment->getCreatedAtDate(), 'medium') ?><span class="separator">|</span><small>
            <?php if (isset($role)): ?>
            	<?php echo $this->escapeHtml($role) ?>
            <?php else: ?>
            	<?php echo $this->helper('sales')->__('Customer') ?>
            <?php endif ?>
            <strong class="subdue">
            <?php if ($_comment->getIsCustomerNotified()): ?>
            	<?php echo $this->helper('sales')->__('Notified') ?>
            	<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
            <?php elseif (isset($send) && $send == 0): ?>
                <?php echo $this->helper('sales')->__('Not Notified') ?>
                <!--img style="position:relative;top:2px;" src="<?php // echo $this->getSkinUrl('images/ico_mobil.png') ?>" width="16" height="16" alt="" /-->
                <img style="position:relative;top:2px;" src="<?php echo $this->getSkinUrl('images/error_msg_icon.gif') ?>" width="16" height="16" alt="" />
          	<?php elseif (isset($send) && $send == 1): ?>
               	<?php echo $this->helper('sales')->__('Notified') ?>
               	<!--img style="position:relative;top:2px;" src="<?php // echo $this->getSkinUrl('images/ico_mobil.png') ?>" width="16" height="16" alt="" /-->
               	<img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
            <?php else: ?>
            	<?php echo $this->helper('sales')->__('Not Notified') ?>
            <?php endif; ?>
            </strong></small>
            <br/>
            <?php echo $this->escapeHtml($text, array('b','br','strong','i','u')) ?>
        </li>
    <?php endforeach; ?>
    </ul>
<script type="text/javascript">
function submitComment() {
    submitAndReloadArea($('comments_block').parentNode, '<?php echo $this->getSubmitUrl() ?>')
}

if ($('submit_comment_button')) {
    $('submit_comment_button').observe('click', submitComment);
}
</script>
</div>
<?php endif; ?>
